apiVersion: v2
type: application
name: kyverno-notation-aws
version: v1.1.0
appVersion: v1.1.0
description: Kyverno extension service for Notation and the AWS signer
keywords:
  - kubernetes
  - nirmata
  - AWS signer
  - notation
